name: sovereigndb
services:
    postgres:
        image: postgres:${POSTGRES_VERSION:-16}
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-symfony}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
            POSTGRES_DB: ${POSTGRES_DB:-sovereigndb}
        healthcheck:
            test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-sovereigndb}", "-U", "${POSTGRES_USER:-symfony}"]
            timeout: 5s
            retries: 5
            start_period: 60s
        networks:
            - sovereignDB

    pgweb:
        restart: always
        image: sosedoff/pgweb
        ports:
            - "8081:8081"
        links:
            - postgres:postgres
        environment:
            - PGWEB_DATABASE_URL=postgres://${POSTGRES_USER:-symfony}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-sovereigndb}?sslmode=disable
        depends_on:
            - postgres

    nginx:
        image: nginx:latest
        volumes:
            - ./nginx/log:/var/log/nginx
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ../../:/var/www/html
        ports:
            - 127.0.0.1:8080:80
        networks:
            - sovereignDB

    php-fpm:
        build: ./php-fpm/
        volumes:
            - ./php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ../../:/var/www/html
        environment:
            POSTGRES_USER: symfony
            POSTGRES_PASSWORD: password
            POSTGRES_DB: sovereigndb
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
        networks:
            - sovereignDB

    symfony:
        image: alpine:latest
        volumes:
            - ../../:/var/www/html
        stop_signal: SIGKILL
        command: tail -f /var/www/html/var/log/dev.log

    mailer:
        image: axllent/mailpit
        ports:
            - 127.0.0.1:1025:1025
            - 127.0.0.1:8025:8025
        environment:
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1
        networks:
            - sovereignDB

volumes:
    postgres-data:

networks:
    sovereignDB:
        external: true