services:
    postgres:
        image: postgres:16
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: symfony
            POSTGRES_PASSWORD: password
            POSTGRES_DB: sovereigndb
    nginx:
        image: nginx:latest
        volumes:
            - ./nginx/log:/var/log/nginx
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ../../:/var/www/html
        ports:
            - 127.0.0.1:8080:80
    php-fpm:
        build: ./php-fpm/
        volumes:
            - ./php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ../../:/var/www/html
        environment:
            POSTGRES_USER: symfony
            POSTGRES_PASSWORD: password
            POSTGRES_DB: sovereigndb
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432

